### ISSUE TITLE
npm ERR! Failed at the pg-query-native@1.2.0 install script.

### ISSUE THREAD

**Issue by akanduri** [zhm/pg-query-native#14]
Hello,
Facing issue in Windows, here is the error, can you please help me on this issue.

Error:

gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
gyp ERR! stack at ChildProcess.emit (events.js:198:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WORKSPACE\Service\node_modules\pg-query-native
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pg-query-native@1.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pg-query-native@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by akanduri** [comment]
could you please provide any solution or workaround, appreciate your help

**Comment by akanduri** [comment]
we are waiting for your response badly, can you please have a look and get back.

**Comment by tatiananeda** [comment]
Experiencing the same in Mac OS Catalina 10.15.7 node 14, npm 6. 
```info lifecycle pg-query-native@1.2.0~install: pg-query-native@1.2.0
9000 verbose lifecycle pg-query-native@1.2.0~install: unsafe-perm in lifecycle true
9001 verbose lifecycle pg-query-native@1.2.0~install: PATH: /Users/.../.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/.../Documents/Service/node_modules/pg-query-native/node_modules/.bin:/Users/.../Documents/Service/node_modules/.bin:/Users/.../.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/.../.nvm/versions/node/v14.16.1/bin
9002 verbose lifecycle pg-query-native@1.2.0~install: CWD: /Users/.../Documents/Service/node_modules/pg-query-native
9003 silly lifecycle pg-query-native@1.2.0~install: Args: [ '-c', 'node-gyp rebuild' ]
9004 silly lifecycle pg-query-native@1.2.0~install: Returned: code: 1  signal: null
9005 info lifecycle pg-query-native@1.2.0~install: Failed to exec install script
9006 verbose teardown shutting down workers.
9007 info teardown Done in 0s
9008 verbose stack Error: pg-query-native@1.2.0 install: `node-gyp rebuild`
9008 verbose stack Exit status 1
9008 verbose stack     at EventEmitter.<anonymous> (/Users/.../.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
9008 verbose stack     at EventEmitter.emit (events.js:315:20)
9008 verbose stack     at ChildProcess.<anonymous> (/Users/.../.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
9008 verbose stack     at ChildProcess.emit (events.js:315:20)
9008 verbose stack     at maybeClose (internal/child_process.js:1048:16)
9008 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
9009 verbose pkgid pg-query-native@1.2.0
9010 verbose cwd /Users/.../Documents/Service
9011 verbose Darwin 19.6.0
9012 verbose argv "/Users/.../.nvm/versions/node/v14.16.1/bin/node" "/Users/.../.nvm/versions/node/v14.16.1/bin/npm" "ci"
9013 verbose node v14.16.1
9014 verbose npm  v6.14.12
9015 error code ELIFECYCLE
9016 error errno 1
9017 error pg-query-native@1.2.0 install: `node-gyp rebuild`
9017 error Exit status 1
9018 error Failed at the pg-query-native@1.2.0 install script.
9018 error This is probably not a problem with npm. There is likely additional logging output above.
9019 verbose exit [ 1, true ]
```
